---
# Which degrees of severity to track
# Possible values: Minor, Moderate, Severe, Extreme
SEVERITY_FILTER:
  - Severe
  - Extreme

# Which states to track
# Possible values: SH, HH, NI, HB, NW, HE, RP, BW, BY, SL, BE, BB, NV, SN, ST, TH
STATES_FILTER:
  - SH
  - HH
  - NI
  - HB
  - NW
  - HE
  - RP
  - BW
  - BY
  - SL
  - BE
  - BB
  - NV
  - SN
  - ST
  - TH

# Which urgency to track
# Possible values: Future ("Vorabinformation") and Immediate ("Warnung")
URGENCY_FILTER:
  - Immediate
